ALTER TABLE "PenaltyShootoutResult"
ADD COLUMN IF NOT EXISTS "suddenDeathScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "suddenDeathShotsJson" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "isWinner" BOOLEAN NOT NULL DEFAULT false;